# Copyright (c) OpenMMLab. All rights reserved.
import torch
import torch.nn as nn
from abc import ABCMeta, abstractmethod
import torch.nn.functional as F
import math

from ...core import top_k_accuracy
from ..builder import build_loss

import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
from pyskl.utils.graph import Graph


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        print("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor

class BaseHead(nn.Module, metaclass=ABCMeta):
    """Base class for head.

    All Head should subclass it.
    All subclass should overwrite:
    - Methods:``init_weights``, initializing weights in some modules.
    - Methods:``forward``, supporting to forward both for training and testing.

    Args:
        num_classes (int): Number of classes to be classified.
        in_channels (int): Number of channels in input feature.
        loss_cls (dict): Config for building loss.
            Default: dict(type='CrossEntropyLoss', loss_weight=1.0).
        multi_class (bool): Determines whether it is a multi-class
            recognition task. Default: False.
        label_smooth_eps (float): Epsilon used in label smooth.
            Reference: arxiv.org/abs/1906.02629. Default: 0.
    """

    def __init__(self,
                 num_classes,
                 in_channels,
                 loss_cls=dict(type='CrossEntropyLoss', loss_weight=1.0),
                 multi_class=False,
                 label_smooth_eps=0.0):
        super().__init__()
        self.num_classes = num_classes
        self.in_channels = in_channels
        self.loss_cls = build_loss(loss_cls)
        self.multi_class = multi_class
        self.label_smooth_eps = label_smooth_eps

        loss_keypoint = dict(type='JointsMSELoss', use_target_weight=True)
        self.loss_1 = build_loss(loss_keypoint)

        graph = Graph(layout='nturgb+d', mode='stgcn_spatial', max_hop=2)
        A = graph.A
        A = A.mean(axis=0)
        A = torch.tensor(A, dtype=torch.float32)
        neighbors = [torch.where(A[v] == 1)[0] for v in range(25)]

        proto = torch.randn(25, 3, 256)  
        proto = F.normalize(_trunc_normal_(proto, mean=0., std=0.02, a=-2., b=2.), dim=2)
        
        for m in range(3):
            for v in range(25):
                if len(neighbors[v]) > 0:
                    neighbor_feats = proto[neighbors[v], m, :]
                    mean_neighbor = neighbor_feats.mean(dim=0)
                    proto[v, m, :] = proto[v, m, :] + mean_neighbor

        self.prototypes = nn.Parameter(proto, requires_grad=False)

        # self.label_map = nn.Parameter(torch.randn(60, 25, 25, 25))
        self.label_map = nn.Parameter(torch.randn(120, 25, 25, 25))

    @abstractmethod
    def init_weights(self):
        """Initiate the parameters either from existing checkpoint or from
        scratch."""

    @abstractmethod
    def forward(self, x, x_p):
        """Defines the computation performed at every call."""

    def loss(self, cls_score, x_p, label, **kwargs):
        """Calculate the loss given output ``cls_score``, target ``label``.

        Args:
            cls_score (torch.Tensor): The output of the model.
            label (torch.Tensor): The target output of the model.

        Returns:
            dict: A dict containing field 'loss_cls'(mandatory)
            and 'top1_acc', 'top5_acc'(optional).
        """
        losses = dict()
        if label.shape == torch.Size([]):
            label = label.unsqueeze(0)
        elif label.dim() == 1 and label.size()[0] == self.num_classes \
                and cls_score.size()[0] == 1:
            label = label.unsqueeze(0)

        if not self.multi_class and cls_score.size() != label.size():
            top_k_acc = top_k_accuracy(cls_score.detach().cpu().numpy(),
                                       label.detach().cpu().numpy(), (1, 5))
            losses['top1_acc'] = torch.tensor(
                top_k_acc[0], device=cls_score.device)
            losses['top5_acc'] = torch.tensor(
                top_k_acc[1], device=cls_score.device)

        elif self.multi_class and self.label_smooth_eps != 0:
            label = ((1 - self.label_smooth_eps) * label + self.label_smooth_eps / self.num_classes)

        loss_cls = self.loss_cls(cls_score, label, **kwargs)
        # loss_cls may be dictionary or single tensor
        if isinstance(loss_cls, dict):
            losses.update(loss_cls)
        else:
            losses['loss_cls'] = loss_cls

        #
        b, c, t, v = x_p.shape
        x_p = x_p.permute(0, 2, 3, 1).contiguous()  # -> (b, t, v, c)
        x_p = x_p.view(b*t*v, c)  # -> (b*t*v, c)

        feats = F.normalize(x_p.type(torch.float32), p=2, dim=-1)
        self.prototypes.data.copy_(F.normalize(self.prototypes, p=2, dim=-1))

        # # k:#joints+bg, m:#in-cls-proto
        sim = torch.einsum('nd,kmd->nmk', feats, self.prototypes)  # (b*t*v,3,25)

        sim_rescale = torch.abs(sim)
        out_cls = torch.amax(sim_rescale, dim=1)
        out_cls = torch.clamp(out_cls, min=1.0e-4, max=1 - 1.0e-4)  #(b*t*v,25)

        out_cls = out_cls.view(b, t, v, 25).permute(0, 3, 1, 2).contiguous()  #(b,25,t,v)
        #
        # ##
        hm_loss = torch.zeros(1, dtype=out_cls.dtype, device=out_cls.device).sum()
        # #label1 = self.class_prototypes[:label.shape[0]]
        label1 = self.label_map[label]  # shape: (B, V1, T, V2)

        hm_loss = hm_loss + self.loss_1(out_cls, label1)
        losses['hm_loss'] = hm_loss

        return losses
